<a href="https://colab.research.google.com/github/Trung0Minh/AIO2023-MODULE-3/blob/main/probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def create_train_data():
    data = [
    ["Sunny", "Hot", "High", "Weak", "no"],
    ["Sunny", "Hot", "High", "Strong", "no"],
    ["Overcast", "Hot", "High", "Weak", "yes"],
    ["Rain", "Mild", "High", "Weak", "yes"],
    ["Rain", "Cool", "Normal", "Weak", "yes"],
    ["Rain", "Cool", "Normal", "Strong", "no"],
    ["Overcast", "Cool", "Normal", "Strong", "yes"],
    ["Overcast", "Mild", "High", "Weak", "no"],
    ["Sunny", "Cool", "Normal", "Weak", "yes"],
    ["Rain", "Mild", "Normal", "Weak", "yes"]
    ]
    return np.array(data)

In [3]:
train_data = create_train_data()
train_data

array([['Sunny', 'Hot', 'High', 'Weak', 'no'],
       ['Sunny', 'Hot', 'High', 'Strong', 'no'],
       ['Overcast', 'Hot', 'High', 'Weak', 'yes'],
       ['Rain', 'Mild', 'High', 'Weak', 'yes'],
       ['Rain', 'Cool', 'Normal', 'Weak', 'yes'],
       ['Rain', 'Cool', 'Normal', 'Strong', 'no'],
       ['Overcast', 'Cool', 'Normal', 'Strong', 'yes'],
       ['Overcast', 'Mild', 'High', 'Weak', 'no'],
       ['Sunny', 'Cool', 'Normal', 'Weak', 'yes'],
       ['Rain', 'Mild', 'Normal', 'Weak', 'yes']], dtype='<U8')

In [8]:
def compute_prior_probability(train_data):
    y_unique = ['no', 'yes']
    prior_probability = np.zeros(len(y_unique))
    prior_probability[0] = len([y[-1] for y in train_data if y[-1] == 'no']) / len(train_data)
    prior_probability[1] = 1 - prior_probability[0]
    return prior_probability

In [9]:
prior_probablity = compute_prior_probability( train_data )
print ("P( play tennis = No)", prior_probablity[0])
print ("P( play tennis = Yes)", prior_probablity[1])

P( play tennis = No) 0.4
P( play tennis = Yes) 0.6


In [56]:
def compute_conditional_probability(train_data):
    y_unique = ['no', 'yes']
    conditional_probability = []
    list_x_name = []

    for i in range(0, train_data.shape[1] - 1):
        x_unique = np.unique(train_data[:, i])
        list_x_name.append(x_unique)

        x_conditional_probability = np.zeros((len(y_unique), len(x_unique)))
        for y in range(len(y_unique)):
            for x in range(len(x_unique)):
                x_conditional_probability[y, x] = len(np.where((train_data[:,i] == x_unique[x]) & (train_data[:, 4] == y_unique[y]))) / len(np.where(train_data[:, 4] == y_unique[y])[0])
        conditional_probability.append(x_conditional_probability)

    return conditional_probability, list_x_name

In [45]:
train_data = create_train_data ()
_, list_x_name = compute_conditional_probability ( train_data )
print ("x1 = ",list_x_name [0])
print ("x2 = ",list_x_name [1])
print ("x3 = ",list_x_name [2])
print ("x4 = ",list_x_name [3])

x1 =  ['Overcast' 'Rain' 'Sunny']
x2 =  ['Cool' 'Hot' 'Mild']
x3 =  ['High' 'Normal']
x4 =  ['Strong' 'Weak']


In [31]:
def getIndexFromValue(featureName, listFeatures):
    return np.where(listFeatures == featureName)[0][0]

In [59]:
train_data = create_train_data ()
_, list_x_name = compute_conditional_probability ( train_data )
outlook = list_x_name[0]
i1 = getIndexFromValue ("Overcast", outlook )
i2 = getIndexFromValue ("Rain", outlook )
i3 = getIndexFromValue ("Sunny", outlook )
print (i1 , i2 , i3)

0 1 2


In [57]:
train_data = create_train_data ()
conditional_probability , list_x_name = compute_conditional_probability (
train_data )
# Compute P(" Outlook "=" Sunny "| Play Tennis "=" Yes ")
x1= getIndexFromValue ("Sunny",list_x_name [0])
print ("P('Outlook' = 'Sunny'| 'Play Tennis' = 'Yes') = ", np. round (
conditional_probability [0][1 , x1 ] ,2))

P('Outlook' = 'Sunny'| 'Play Tennis' = 'Yes') =  0.17


In [50]:
train_data = create_train_data ()
conditional_probability , list_x_name = compute_conditional_probability (
train_data )
# Compute P(" Outlook "=" Sunny "| Play Tennis "=" No ")
x1= getIndexFromValue ("Sunny",list_x_name [0])
print ("P(’ Outlook ’=’ Sunny ’| Play Tennis ’=’No ’) = ", np. round (
conditional_probability [0][1 , x1 ] ,2))

P(’ Outlook ’=’ Sunny ’| Play Tennis ’=’No ’) =  0.1


In [58]:
conditional_probability

[array([[0.25      , 0.25      , 0.25      ],
        [0.16666667, 0.16666667, 0.16666667]]),
 array([[0.25      , 0.25      , 0.25      ],
        [0.16666667, 0.16666667, 0.16666667]]),
 array([[0.25      , 0.25      ],
        [0.16666667, 0.16666667]]),
 array([[0.25      , 0.25      ],
        [0.16666667, 0.16666667]])]

In [52]:
def train_naive_bayes(train_data):
    y_unique = ['no', 'yes']
    prior_probablity = compute_prior_probability(train_data)
    conditional_probability, list_x_name = compute_conditional_probability(train_data)
    return prior_probablity, conditional_probability, list_x_name

In [55]:
list_x_name

[array(['Overcast', 'Rain', 'Sunny'], dtype='<U8'),
 array(['Cool', 'Hot', 'Mild'], dtype='<U8'),
 array(['High', 'Normal'], dtype='<U8'),
 array(['Strong', 'Weak'], dtype='<U8')]

In [60]:
def prediction_play_tennis(X, list_x_name, prior_probability, conditional_probability):
    x1 = getIndexFromValue(X[0], list_x_name[0])
    x2 = getIndexFromValue(X[1], list_x_name[1])
    x3 = getIndexFromValue(X[2], list_x_name[2])
    x4 = getIndexFromValue(X[3], list_x_name[3])

    p0 = 0
    p1 = 0

    p0 = prior_probability[0] * conditional_probability[0][0, x1] * conditional_probability[1][0, x2] * conditional_probability[2][0, x3] * conditional_probability[3][0, x4]
    p1 = prior_probability[1] * conditional_probability[0][1, x1] * conditional_probability[1][1, x2] * conditional_probability[2][1, x3] * conditional_probability[3][1, x4]

    if p0 > p1:
        y_pred = 0
    else:
        y_pred = 1
    return y_pred

In [61]:
X = ['Sunny','Cool', 'High', 'Strong']
data = create_train_data ()
prior_probability , conditional_probability , list_x_name = train_naive_bayes ( data )
pred = prediction_play_tennis (X, list_x_name , prior_probability ,
conditional_probability )
if( pred ):
    print ("Ad should go!")
else :
    print ("Ad should not go!")

Ad should not go!


# Iris flower

In [10]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('iris.data.txt')
data

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [6]:
data.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
data

sepal_length  sepal_width  petal_length  petal_width         species
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

In [7]:
data['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [8]:
def compute_prior_probability_flower(data):
    y_unique = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
    prior_probability = np.zeros(len(y_unique))
    for y in range(len(y_unique)):
        prior_probability[y] = len(data[data['species'] == y_unique[y]]) / len(data)
    return prior_probability

In [13]:
prior_prbability = compute_prior_probability_flower(data)
prior_prbability

array([0.32885906, 0.33557047, 0.33557047])

In [14]:
def gaussian_distribution(x, mean, std):
    return (1 / (np.sqrt(2 * np.pi) * std)) * np.exp(-((x - mean) ** 2) / (2 * std ** 2))

In [38]:
def calculate_mean_and_std(data):
    mean = []
    std = []
    for flower in data['species'].unique():
        mean.append(np.mean(data[data['species'] == flower].iloc[:,:-1], axis=0))
        std.append(np.std(data[data['species'] == flower].iloc[:,:-1], axis=0))
    return mean, std

In [40]:
mean, std = calculate_mean_and_std(data)
std

[sepal_length    0.352229
 sepal_width     0.380841
 petal_length    0.173265
 petal_width     0.107021
 dtype: float64,
 sepal_length    0.510983
 sepal_width     0.310644
 petal_length    0.465188
 petal_width     0.195765
 dtype: float64,
 sepal_length    0.629489
 sepal_width     0.319255
 petal_length    0.546348
 petal_width     0.271890
 dtype: float64]

In [49]:
def compute_result_flower(X, data, mean, std):
    y_unique = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
    prior_probability = compute_prior_probability_flower(data)
    mean, std = calculate_mean_and_std(data)
    p = []

    for y in range(len(y_unique)):
        prob = 1
        for x in range(len(X)):
            prob *= gaussian_distribution(X[x], mean[y][x], std[y][x])
        prob *= prior_probability[y]
        p.append(prob)
    return y_unique[np.argmax(p)]

In [50]:
X = [4.9 ,3.1 ,1.5 ,0.1]
result = compute_result_flower(X, data, mean, std)
result

<ipython-input-49-99f48ec89d1d>:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prob *= gaussian_distribution(X[x], mean[y][x], std[y][x])


'Iris-setosa'